name: in-context-learning
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - flit-core=3.8.0=py38h06a4308_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuv=1.44.2=h5eee18b_0
  - mkl=2022.1.0=hc2b9512_224
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py38h06a4308_0
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.1
    - bleach==6.0.0
    - cerberus==1.3.2
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - comm==0.1.3
    - cycler==0.11.0
    - cytoolz==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - filelock==3.10.7
    - fonttools==4.39.3
    - fqdn==1.5.1
    - funcy==1.15
    - gin-config==0.3.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - huggingface-hub==0.13.3
    - idna==3.4
    - importlib-metadata==6.1.0
    - importlib-resources==5.12.0
    - ipykernel==6.22.0
    - ipython==8.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.1.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - munch==2.5.0
    - nbclassic==0.5.5
    - nbclient==0.7.3
    - nbconvert==7.3.0
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - numpy==1.22.3
    - packaging==23.0
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.2.0
    - prometheus-client==0.16.0
    - promise==2.3
    - prompt-toolkit==3.0.38
    - protobuf==3.20.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pyyaml==5.4
    - pyzmq==25.0.2
    - qtconsole==5.4.2
    - qtpy==2.3.1
    - quinine==0.3.0
    - regex==2023.3.23
    - requests==2.28.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - sacremoses==0.0.53
    - scikit-learn==1.0.2
    - scipy==1.10.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentry-sdk==1.19.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - termcolor==2.2.0
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - toolz==0.12.0
    - toposort==1.5
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.9.0
    - transformers==4.17.0
    - uri-template==1.2.0
    - urllib3==1.26.15
    - wandb==0.12.11
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.7
    - xgboost==1.6.1
    - yaspin==2.3.0
    - zipp==3.15.0
prefix: /private/home/kartikahuja/.conda/envs/in-context-learning
